### PR TITLE
issue 158: Add SmallState

### LINKED ISSUE #158: Consider reducing the size of RandomState
Do you think it's possible to reduce the size of RandomState? Could ahash get away with only 16 bytes maybe?  Right now it's 32 bytes long, which is twice as much as the std lib version.

This might seem inconsequential, but it can add significant overhead when ahash hashmaps are used inside repeated/nested structures.

### PR DESCRIPTION
**Pull request by tkaitchuck**
Is an optional reduced size state.
Fixes #158

### CODE REVIEW

**Comment by arthurprs** [comment]
I performed a quick benchmark with runtime-rng enabled (the most common feature I suppose) and the time to hash a 10 byte string goes from 2.5ns to 12.3ns, which puts it in siphash territory.

Do you think we could take some liberties with the creation of RandomState from SmallState, like

```
        let [a, _] = get_fixed_seeds();
        AHasher::from_random_state(&RandomState {
            k0: self.key as u64 ^ a[0],
            k1: self.key as u64 ^ a[1],
            k2: self.key as u64 ^ a[2],
            k3: self.key as u64 ^ a[3],
            _h: PhantomData::<T>,
        })
```

This brings it down from 12ns to 4ns

**Comment by tkaitchuck** [comment]
@arthurprs The code you have there won't work. But I have tried to speed it up. Give it another try.

**Comment by arthurprs** [comment]
I got 7ns for 3e14ceb and 6.3ns for 1e94eac.
For context, it's 2.5ns for the regular ahash and 10.3ns for sip13.

I think it's good now, unless you can squeeze more out of it :rocket:

**Comment by tkaitchuck** [comment]
I think I should be able to lower the added overhead by another 20%.

**Comment by tkaitchuck** [comment]
@arthurprs Is [e2ae7b7](https://github.com/tkaitchuck/aHash/pull/226/commits/e2ae7b75674a29cc77fd764afab0a5efc4522f5c) any faster on your system? It *should* be, but it my tests it appears to be, but only by about the same margin as random noise.

**Comment by arthurprs** [comment]
I can confirm the latest commit is 12% faster than the previous (~5ns).

**Pull request merged**
