### PR TITLE
Increase the MSRV presubmit checks to include multiple architectures

### PR DESCRIPTION
**Pull request by tkaitchuck**

### CODE REVIEW

**Comment by alamb** [comment]
https://github.com/tkaitchuck/aHash/actions/runs/7449693417/job/20266892686?pr=197#step:5:1

Seems to imply it just installed 1.60 in addition to the master build already installed

Maybe you need to change 
```shell
  cargo check --target armv7-unknown-linux-gnueabihf
```

To explicitly mention the tool chain like 
```shell
  cargo +1.60 check --target armv7-unknown-linux-gnueabihf
```


FWIW we use cargo msrv  to check this in datafusion

https://github.com/apache/arrow-datafusion/blob/746988a7e5c9f256c3b24ab7e3f30ffd90d542a0/.github/workflows/rust.yml#L546-L568

**Comment by tkaitchuck** [comment]
It runs `rustup default 1.60.0` is this insufficient?

**Comment by tkaitchuck** [comment]
I added this, everything is still passing...

**Comment by tkaitchuck** [comment]
It looks like it used to pass with 1.60 but then failed with 1.71
So the command was correct, it was just a discrepancy in what rust supported.

**Comment by alamb** [comment]
🎉

**Pull request merged**
